format = "$directory$all$character"

[character]
success_symbol = "[|](bold green)ğŸ›¹" # ğŸ›¹ is a skateboard utf8 emoji
error_symbol = "[|](bold green)âŒ"

[directory]
format = "[$path](bold purple)[$read_only]($read_only_style) "
truncation_symbol = "../"

[git_branch]
format = "on [$symbol$branch](bold blue) "
style = "bold yellow"
